### ISSUE TITLE
object allocated on the heap may not be aligned 64

### ISSUE THREAD

**Issue by m0vse** [kmdreko/wilt-ring#1]
Hi.

I am successfully using your ring buffer and it is great! I do notice that when I compile on Windows (MSVC2019) I receive the warning:

 `warning C4316: 'wilt::Ring<audioPacket>': object allocated on the heap may not be aligned 64`

Is there a workaround for this or can it safely be ignored?

Thanks

Phil

**Comment by kmdreko** [comment]
The class uses 64-byte alignment to ensure fields lie on different cache-lines. But since this is only a performance consideration, this warning can probably be safely ignored. The underlying fields only require an 8-byte alignment.

**Comment by kmdreko** [comment]
Also, I'd like to direct you towards a blog post I wrote on this library: [A Simple Lock-free Ring Buffer](https://kmdreko.github.io/posts/20191003/a-simple-lock-free-ring-buffer/#Performance). This implementation has very poor performance characteristics under contention so I wouldn't recommend using it for anything important.
